# Generated by Django 4.2.19 on 2025-04-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryhistory',
            name='action',
            field=models.CharField(choices=[('add', 'Added'), ('update', 'Updated'), ('delete', 'Deleted'), ('archive', 'Archive'), ('unarchive', 'Unarchive'), ('stk added', 'Stk Added'), ('stk delete', 'Stk Delete')], max_length=10),
        ),
    ]
