# Generated by Django 4.2.19 on 2025-04-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryhistory',
            name='item',
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='location',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
