# Generated by Django 4.2.19 on 2025-04-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_remove_inventoryhistory_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryhistory',
            name='individual_item_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='item_class_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
