# Generated by Django 4.2.19 on 2025-04-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_inventoryhistory_individual_item_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryhistory',
            name='individual_item_number',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='item_class_number',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
