# Generated by Django 4.2.19 on 2025-04-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_alter_inventoryhistory_individual_item_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryhistory',
            name='action',
            field=models.CharField(choices=[('add', 'Added'), ('update', 'Updated'), ('delete', 'Deleted'), ('archive', 'Archive')], max_length=10),
        ),
    ]
