# Generated by Django 4.2.19 on 2025-02-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
