# Generated by Django 4.2.19 on 2025-04-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invtable_metadata',
            name='company_name',
            field=models.CharField(default='Default Company', max_length=255),
        ),
    ]
