# Generated by Django 5.1.5 on 2025-04-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0002_rename_table_location_invtable_metadata_table_friendly_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitem',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
