# Generated by Django 4.2.19 on 2025-03-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0003_rename_todoitem_invitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invitem',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
