# Generated by Django 4.2.19 on 2025-03-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0004_alter_invitem_quantity_alter_invitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitem',
            name='custom_fields',
            field=models.JSONField(default=dict),
        ),
    ]
