# Generated by Django 4.2.19 on 2025-03-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0005_invitem_custom_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvTable_Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255, unique=True)),
                ('table_type', models.CharField(max_length=50)),
                ('table_location', models.CharField(max_length=255)),
            ],
        ),
    ]
