# Generated by Django 4.2.19 on 2025-03-08 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0006_invtable_metadata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invtable_metadata',
            table='invtable_metadata',
        ),
    ]
