# Generated by Django 4.2.19 on 2025-03-08 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0007_alter_invtable_metadata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invtable_metadata',
            table=None,
        ),
    ]
