# Generated by Django 5.1.5 on 2025-03-11 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_analysis', '0003_alter_inventoryitem_category_salerecord_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleRecord',
        ),
    ]
