# Generated by Django 5.1.5 on 2025-04-20 05:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(help_text='The id of the row in the class table')),
                ('change', models.IntegerField(help_text='Positive for add, negative for remove')),
                ('tracking_id', models.CharField(db_index=True, help_text='Unique identifier for each physical unit (reused in tx log)', max_length=255)),
                ('transaction_id', models.CharField(db_index=True, default=uuid.uuid4, help_text='UUID for this transaction event', max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table_meta', models.ForeignKey(help_text='Which inventory class this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.invtable_metadata')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['table_meta', 'item_id'], name='updateStock_table_m_425390_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockUnit',
            fields=[
                ('item_id', models.IntegerField(help_text='Which master row this unit belongs to')),
                ('tracking_id', models.CharField(help_text='Unique identifier for this physical unit', max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(default='In Stock', help_text='e.g. In Stock, Removed, Damaged…', max_length=50)),
                ('location', models.CharField(default='Warehouse', help_text='Where it lives right now', max_length=100)),
                ('table_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.invtable_metadata')),
            ],
            options={
                'indexes': [models.Index(fields=['table_meta', 'item_id'], name='updateStock_table_m_3a62a4_idx')],
                'unique_together': {('table_meta', 'item_id', 'tracking_id')},
            },
        ),
    ]
