# Generated by Django 5.1.5 on 2025-04-19 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0002_invtable_metadata_company_name'),
        ('updateStock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='tracking_id',
            field=models.CharField(db_index=True, help_text='Unique identifier for each physical unit (reused in tx log)', max_length=255),
        ),
        migrations.CreateModel(
            name='StockUnit',
            fields=[
                ('item_id', models.IntegerField(help_text='Which master row this unit belongs to')),
                ('tracking_id', models.CharField(help_text='Unique identifier for this physical unit', max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(default='In Stock', help_text='e.g. In Stock, Removed, Damaged…', max_length=50)),
                ('location', models.CharField(default='Warehouse', help_text='Where it lives right now', max_length=100)),
                ('table_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.invtable_metadata')),
            ],
            options={
                'indexes': [models.Index(fields=['table_meta', 'item_id'], name='updateStock_table_m_3a62a4_idx')],
                'unique_together': {('table_meta', 'item_id', 'tracking_id')},
            },
        ),
    ]
