# Generated by Django 4.2.19 on 2025-04-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='company',
            field=models.CharField(default='defautl', max_length=255),
        ),
    ]
