# Generated by Django 4.2.19 on 2025-04-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportticket_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='user_email',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user_phone',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
