# Generated by Django 4.2.19 on 2025-04-21 01:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AT_SUPPLIER', 'At Supplier'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received')], default='AT_SUPPLIER', max_length=20)),
                ('destination_percentage', models.PositiveIntegerField(default=0)),
                ('location_name', models.CharField(default='Unknown', max_length=255)),
                ('tracking_number', models.CharField(editable=False, help_text='Auto-generated order tracking number', max_length=32, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Time this order was created')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('inventory_item', models.ForeignKey(help_text='Which product is being ordered', on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.invitem')),
                ('supply_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='suppliers.supplyorder')),
            ],
        ),
    ]
