# Generated by Django 5.1.7 on 2025-03-23 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='supplyorder',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='supplyorderitem',
            name='cost_per_item',
        ),
        migrations.AlterField(
            model_name='supplyorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplyorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_orders', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='supplyorderitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
