# Generated by Django 5.1.5 on 2025-04-20 18:01

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Time this order was created'),
        ),
        migrations.AlterField(
            model_name='supplyorder',
            name='location_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplyorder',
            name='tracking_number',
            field=models.CharField(default=uuid.uuid4, editable=False, help_text='Auto-generated order tracking number', max_length=32, unique=True),
        ),
    ]
