# Generated by Django 5.1.5 on 2025-04-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplyorder_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyorder',
            name='tracking_number',
            field=models.CharField(editable=False, help_text='Auto-generated order tracking number', max_length=32, unique=True),
        ),
    ]
