# Generated by Django 5.1.5 on 2025-04-20 18:07

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_supplyorder_tracking_number'),
        ('suppliers', '0004_auto_20250420_1806'),
    ]

    operations = [
        # 1) Drop invalid default at the SQL level
        migrations.RunSQL(
            sql="ALTER TABLE suppliers_supplyorder ALTER tracking_number DROP DEFAULT;",
            reverse_sql="ALTER TABLE suppliers_supplyorder ALTER tracking_number SET DEFAULT '';"
        ),
        # 2) Then apply the AlterField from 0003 or 0004 as appropriate—
        #    you might need to copy the AlterField operation here if Django didn’t auto-include it.
        #    For example:
        migrations.AlterField(
            model_name='supplyorder',
            name='tracking_number',
            field=models.CharField(
                max_length=32,
                unique=True,
                editable=False,
                help_text='Auto‑generated order tracking number'
            ),
        ),
    ]
